### ISSUE TITLE
Git > README.md

### ISSUE THREAD

**Issue by johannpinson** [AnnaBmnn/hetic-p2020-07#1]
As ask you Bastien, don't forget to add quickly a README.md, with for example :

- [ ] Use section to discern the different parts
- [ ] With must see at minimal 3 parts "how to" : Installation, Running and Building the app
- [ ] Add precision about (S)CSS naming convention (BEM ? OCCSS ? etc.)
- [ ] Don't forget to specify any requirement (node.js >= 6.4 ? npm -g yarn ? etc.)
- [ ] You can add anything else useful (credit, git commit msg convention, badge, logo, screenshot, etc.)

**Comment by johannpinson** [comment]
up!

**Comment by johannpinson** [comment]
up!

**Comment by johannpinson** [comment]
I don't think it's normal to see the file inside the `master` but not the `dev` branch...

**Comment by MinDBreaK** [comment]
This has been corrected, thanks !
