### ISSUE TITLE
Assets > img

### ISSUE THREAD

**Issue by johannpinson** [AnnaBmnn/hetic-p2020-07#12]
See https://github.com/AnnaBmnn/hetic-p2020-07/tree/dev/src/img

The name of images shouldn't use capital letter.
Use a convention with a `-` or `_`.

**Comment by johannpinson** [comment]
Edit:
You must harmonize because i see `balle_de_tennis.png` and `chocolat-1.png`

And use english for naming like you make with the `flower.png`

**Comment by MinDBreaK** [comment]
The assets should have been translated now, thanks for pointing this out !
