### ISSUE TITLE
Git > Integration branch

### ISSUE THREAD

**Issue by johannpinson** [AnnaBmnn/hetic-p2020-07#2]
What is the `integration` branch?

**Comment by AnnaBmnn** [comment]
It's a branch dedicate for the integration of the parfum product page, maybe the name is not relevant enough

**Comment by johannpinson** [comment]
By convention, the branch will be name `feature-fragrance` or `feature-product_page`

**Comment by AnnaBmnn** [comment]
Is it possible to change the name of the branch ?

**Comment by MinDBreaK** [comment]
Branch as been renamed to a conventionned name, closing the issue.
