### ISSUE TITLE
Browserslist

### ISSUE THREAD

**Issue by johannpinson** [AnnaBmnn/hetic-p2020-07#4]
https://github.com/AnnaBmnn/hetic-p2020-07/blob/49cf0a8f29a039b1b2e520635077e1b5fe95fe76/.browserlistrc#L1

=> 

https://github.com/ai/browserslist/issues/138

**Comment by johannpinson** [comment]
Some input => the content of the fil isn't wrong, but it miss an 's' inside the name of the file

**Comment by johannpinson** [comment]
Some help => the content of the file isn't wrong, but it miss an 's' inside the name of the file

**Comment by johannpinson** [comment]
<img width="573" alt="capture d ecran 2017-11-24 a 16 56 14" src="https://user-images.githubusercontent.com/2202989/33217467-675ef4fc-d138-11e7-9120-d0ac86dc2427.png">

**Comment by johannpinson** [comment]
;-)

**Comment by MinDBreaK** [comment]
This file has been renamed, thanks !
